services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - uploads_data:/app/uploads
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT:-3001}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads_data:
  backend_node_modules: 